name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 
  test:
    name: Test
    runs-on: ubuntu-latest
     services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: mybank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
 